export const CARGO_CATEGORIES = [
  'GeneralGoods',
  'Perishable',
  'Hazardous',
  'HighValue',
  'Pharmaceutical',
  'Electronics',
] as const;

export const SHIPMENT_STATUS = [
  'Draft',
  'Submitted',
  'InspectionPending',
  'CustomsReview',
  'Cleared',
  'InTransit',
  'InCustody',
  'Delivered',
  'Lost',
] as const;

export const CIPHERED_SUPPLY_LEDGER_ABI = [
  {
    type: 'event',
    name: 'ShipmentSubmitted',
    inputs: [
      { indexed: true, name: 'shipmentId', type: 'bytes32' },
      { indexed: true, name: 'shipper', type: 'address' },
      { indexed: false, name: 'category', type: 'uint8' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ShipmentStatusChanged',
    inputs: [
      { indexed: true, name: 'shipmentId', type: 'bytes32' },
      { indexed: false, name: 'oldStatus', type: 'uint8' },
      { indexed: false, name: 'newStatus', type: 'uint8' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'QualityInspectionCompleted',
    inputs: [
      { indexed: true, name: 'shipmentId', type: 'bytes32' },
      { indexed: false, name: 'inspector', type: 'address' },
      { indexed: false, name: 'passed', type: 'bool' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CustomsClearanceRequested',
    inputs: [
      { indexed: true, name: 'shipmentId', type: 'bytes32' },
      { indexed: false, name: 'requestId', type: 'uint256' },
      { indexed: false, name: 'officer', type: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CustomsClearanceCompleted',
    inputs: [
      { indexed: true, name: 'shipmentId', type: 'bytes32' },
      { indexed: false, name: 'clearanceStatus', type: 'uint8' },
      { indexed: false, name: 'finalWeight', type: 'uint64' },
      { indexed: false, name: 'complianceScore', type: 'uint64' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CheckpointRecorded',
    inputs: [
      { indexed: true, name: 'shipmentId', type: 'bytes32' },
      { indexed: false, name: 'checkpointNumber', type: 'uint256' },
      { indexed: false, name: 'recorder', type: 'address' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ShipmentDelivered',
    inputs: [
      { indexed: true, name: 'shipmentId', type: 'bytes32' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'InsuranceClaimFiled',
    inputs: [
      { indexed: true, name: 'shipmentId', type: 'bytes32' },
      { indexed: false, name: 'claimant', type: 'address' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'grantCustomsOfficer',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'grantQualityInspector',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'grantLogisticsManager',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitShipment',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'shipmentId', type: 'bytes32' },
      { name: 'carrier', type: 'address' },
      { name: 'receiver', type: 'address' },
      { name: 'encryptedWeight', type: 'uint256' },
      { name: 'weightProof', type: 'bytes' },
      { name: 'encryptedVolume', type: 'uint256' },
      { name: 'volumeProof', type: 'bytes' },
      { name: 'encryptedValue', type: 'uint256' },
      { name: 'valueProof', type: 'bytes' },
      { name: 'encryptedQuantity', type: 'uint256' },
      { name: 'quantityProof', type: 'bytes' },
      { name: 'encryptedTemperature', type: 'uint256' },
      { name: 'temperatureProof', type: 'bytes' },
      { name: 'encryptedHumidity', type: 'uint256' },
      { name: 'humidityProof', type: 'bytes' },
      { name: 'encryptedFragility', type: 'uint256' },
      { name: 'fragilityProof', type: 'bytes' },
      { name: 'encryptedPriority', type: 'uint256' },
      { name: 'priorityProof', type: 'bytes' },
      { name: 'encryptedRisk', type: 'uint256' },
      { name: 'riskProof', type: 'bytes' },
      { name: 'category', type: 'uint8' },
    ],
    outputs: [{ name: 'shipmentKey', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'conductQualityInspection',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'shipmentId', type: 'bytes32' },
      { name: 'encryptedActualTemp', type: 'uint256' },
      { name: 'tempProof', type: 'bytes' },
      { name: 'encryptedActualHumidity', type: 'uint256' },
      { name: 'humidityProof', type: 'bytes' },
      { name: 'encryptedCondition', type: 'uint256' },
      { name: 'conditionProof', type: 'bytes' },
      { name: 'encryptedPackaging', type: 'uint256' },
      { name: 'packagingProof', type: 'bytes' },
      { name: 'encryptedDocumentation', type: 'uint256' },
      { name: 'documentationProof', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'requestCustomsClearance',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'shipmentId', type: 'bytes32' }],
    outputs: [{ name: 'requestId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'recordCheckpoint',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'shipmentId', type: 'bytes32' },
      { name: 'locationCode', type: 'uint256' },
      { name: 'locationProof', type: 'bytes' },
      { name: 'temperature', type: 'uint256' },
      { name: 'temperatureProof', type: 'bytes' },
      { name: 'humidity', type: 'uint256' },
      { name: 'humidityProof', type: 'bytes' },
      { name: 'scanTime', type: 'uint256' },
      { name: 'scanProof', type: 'bytes' },
      { name: 'handlerId', type: 'uint256' },
      { name: 'handlerProof', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'markDelivered',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'shipmentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'fileInsuranceClaim',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'shipmentId', type: 'bytes32' },
      { name: 'claimAmount', type: 'uint256' },
      { name: 'amountProof', type: 'bytes' },
      { name: 'damagePercent', type: 'uint256' },
      { name: 'damageProof', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getShipmentInfo',
    stateMutability: 'view',
    inputs: [{ name: 'shipmentId', type: 'bytes32' }],
    outputs: [
      { name: 'shipper', type: 'address' },
      { name: 'carrier', type: 'address' },
      { name: 'receiver', type: 'address' },
      { name: 'category', type: 'uint8' },
      { name: 'status', type: 'uint8' },
      { name: 'submittedAt', type: 'uint256' },
      { name: 'clearedAt', type: 'uint256' },
      { name: 'deliveredAt', type: 'uint256' },
      { name: 'isActive', type: 'bool' },
      { name: 'isInsured', type: 'bool' },
      { name: 'statusChangeCount', type: 'uint16' },
      { name: 'checkpointCount', type: 'uint16' },
    ],
  },
  {
    type: 'function',
    name: 'getClearanceInfo',
    stateMutability: 'view',
    inputs: [{ name: 'shipmentId', type: 'bytes32' }],
    outputs: [
      { name: 'clearanceStatus', type: 'uint8' },
      { name: 'finalWeight', type: 'uint64' },
      { name: 'complianceScore', type: 'uint64' },
      { name: 'insuranceEligibility', type: 'uint8' },
      { name: 'isDecrypted', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'getInspectionInfo',
    stateMutability: 'view',
    inputs: [{ name: 'shipmentId', type: 'bytes32' }],
    outputs: [
      { name: 'inspector', type: 'address' },
      { name: 'passed', type: 'bool' },
      { name: 'complete', type: 'bool' },
      { name: 'inspectedAt', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getCheckpointCount',
    stateMutability: 'view',
    inputs: [{ name: 'shipmentId', type: 'bytes32' }],
    outputs: [{ name: 'count', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getCheckpoint',
    stateMutability: 'view',
    inputs: [
      { name: 'shipmentId', type: 'bytes32' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [
      { name: 'recordedAt', type: 'uint256' },
      { name: 'recordedBy', type: 'address' },
      { name: 'isVerified', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'getClaimInfo',
    stateMutability: 'view',
    inputs: [{ name: 'shipmentId', type: 'bytes32' }],
    outputs: [
      { name: 'claimant', type: 'address' },
      { name: 'filedAt', type: 'uint256' },
      { name: 'approved', type: 'bool' },
      { name: 'processed', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'getSupplyChainStats',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'totalShipments', type: 'uint256' },
      { name: 'delivered', type: 'uint256' },
      { name: 'lost', type: 'uint256' },
    ],
  },
];

